[default.extend-words]

[files]
extend-exclude = [
    "CHANGELOG.md",
    "notebooks/*",
    "README.md",
    "migration/*",
    "chat_server/fixtures/*",
    "chat_core/fixtures/*",
    "notify_server/*.html"
  ]
